[package]
name = "cyber-dungeon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.87"

[dev-dependencies]
wasm-pack = "0.12.1"
